server:
  port: 8081

spring:
  liquibase:
    enabled: false

  datasource:
    # connect to DB by JDBC driver
    url: jdbc:mysql://localhost:3306/java_web_app
    username: qa
    password: password
  jpa:
    show-sql: true
